version: '3.9'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v4.14.4
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.20.1
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    environment:
      SWAGGER_JSON: /openapi.yml
    volumes:
      - ./todo-api/schema/openapi.yml:/openapi.yml

  redoc:
    image: redocly/redoc:v2.4.0
    container_name: "redoc"
    environment:
      - SPEC_URL=/openapi/openapi.yml
    volumes:
      - ./todo-api/schema/openapi.yml:/usr/share/nginx/html/openapi/openapi.yml
    ports:
      - "8003:80"

  mock-api:
    image: stoplight/prism:5.12.1
    container_name: "swagger-api"
    ports:
      - "8004:4010"
    command: mock -h 0.0.0.0 /openapi.yml
    volumes:
      - ./todo-api/schema/openapi.yml:/openapi.yml
