openapi: 3.0.3
info:
  version: 0.0.0
  title: API
  description: |-
    This is a sample OpenAPI 3.0 specification.
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: https://example.com/api/v1
tags:
  - name: sample
paths:
  /hello:
    get:
      tags:
        - sample
      summary: Hello World
      operationId: helloWorld
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Hello World!
