name: Hello World

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
      - synchronize

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"